from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('papers/', views.papers, name='papers'),
    path('semester1/', views.semester1, name='semester1'),
    path('semester2/', views.semester2, name='semester2'),
    path('semester3/', views.semester3, name='semester3'),
    path('semester4/', views.semester4, name='semester4'),
    path('semester5/', views.semester5, name='semester5'),
    path('semester6/', views.semester6, name='semester6'),
    path('notes/', views.notes, name='notes'),
    path('paper1/', views.paper1, name='paper1'),
    path('paper2/', views.paper2, name='paper2'),
    path('paper3/', views.paper3, name='paper3'),
    path('paper4/', views.paper4, name='paper4'),
    path('paper5/', views.paper5, name='paper5'),
    path('paper6/', views.paper6, name='paper6'),
    path('cookies/', views.cookies, name='cookies'),
    path('disclaimer/', views.disclaimer, name='disclaimer'),
    path('term/', views.term, name='term'),
    path('pravacy_policy/', views.pravacy_policy, name='pravacy_policy'),
    path('team/', views.team, name='team'),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('profile/', views.profile, name='profile'),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("teacher_dashboard/", views.teacher_dashboard, name="teacher_dashboard"),
    path("teacher_login/", views.teacher_login, name="teacher_login"),
    path("teacher_change_password/",views.teacher_change_password,name="teacher_change_password"),
    path("manage_students/",views.manage_students,name="manage_students"),
    path("manual_attendance/",views.manual_attendance,name="manual_attendance"),
    path("teacher_marks/",views.teacher_marks,name="teacher_marks"),
    path("marks/", views.marks, name="marks"),
    path("teacher_library/", views.teacher_library, name="teacher_library"),
    path("library/",views.library,name="library"),
    # path("attendance_report/",views.attendance_report,name="attendance_report"),
    path("start_attendance/",views.start_attendance,name="start_attendance",),
    path("face_attendance/",views.face_attendance,name="face_attendance",),
    path("attendance/",views.attendance,name="attendance",),
    path("attendance_report/", views.attendance_report, name="attendance_report"),
]