# Generated by Django 6.0.6 on 2026-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('class_roll_number', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=20)),
            ],
        ),
    ]
