# Generated by Django 6.0.6 on 2026-07-10 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('university_roll_number', models.CharField(blank=True, max_length=12, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=13, null=True)),
                ('class_roll_number', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('session', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
