# Generated by Django 6.0.6 on 2026-07-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_student_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_Master',
            new_name='student_master',
        ),
    ]
