# Generated by Django 6.0.6 on 2026-07-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_internalmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_roll_number', models.PositiveIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('book_id', models.CharField(max_length=50)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
    ]
