# Generated by Django 6.0.7 on 2026-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_attendancesession_faceattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='duration',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
